version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: technoparkweb
    ports:
      - "9001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  keycloak:
    image: sleighzy/keycloak
    container_name: technoparkweb-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: technoparkweb
      DB_USER: k_app
      DB_PASSWORD: 123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "9002:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"
  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technoparkweb-app
    environment:
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
    ports:
      - "9000:8080"
    depends_on:
      - postgres
      - keycloak
volumes:
  db-data: