version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: technoparkweb
    ports:
      - "9001:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped
  your-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: technoparkweb-app
    environment:
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
    ports:
      - "9000:8080"
    depends_on:
      - postgres
volumes:
  db-data: