spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:technoparkweb}
    username: ${DATABASE_USERNAME:k_app}
    password: ${DATABASE_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:http://localhost:9002/auth/realms/technoparkweb}
          jwk-set-uri: ${OAUTH2_JWK:http://localhost:9002/auth/realms/technoparkweb/protocol/openid-connect/certs}

application:
  title: Project By TechnoPark
  version: 1.0.0
